volumes:
  acme-vol:
    name: ${ACME_VOL_NAME}
    driver: ${DEV_VOL_DRIVER:-local}
    driver_opts:
      type: ${VOL_TYPE:-nfs}
      o: addr=${VOL_ADDR:-127.0.0.1},vers=${VOL_VERS:-4.2},${VOL_OPTS:-nolock,noacl,noatime,nodiratime}
      device: :${VOL_DEVICE_PREFIX}${ACME_VOL_DEVICE:-/acme-vol/}
