services:
  nginx-proxy-http:
    deploy:
      placement:
        constraints:
          - engine.labels.availability_zone == ${AWS_REGION}a

volumes:
  acme-vol:
    name: ${ACME_VOL_NAME}

configs:
  redirect-redmic-config:
    name: ${REDIRECT_REDMIC_CONFIG_NAME}
    file: ./config/pro-redirect-redmic.conf
