version: '3.5'

services:
  nginx-proxy-http:
    deploy:
      placement:
        constraints:
          - node.labels.${PLACEMENT_CONSTRAINTS_NODE_LABELS_NAME:-gateway} == ${PLACEMENT_CONSTRAINTS_NODE_LABELS_VALUE:-true}

volumes:
  acme-vol:
    name: ${ACME_VOL_NAME}
    driver: local
    driver_opts:
      type: ${ACME_VOL_TYPE:-nfs4}
      o: addr=${ACME_VOL_ADDR:-127.0.0.1},${ACME_VOL_OPTIONS:-rw,nolock,noatime,tcp,rsize=8192,wsize=8192,timeo=14}
      device: ${ACME_VOL_DEVICE:-:/acme-vol/}
