version: '3.5'

services:
  nginx-proxy-http:
    deploy:
      placement:
        constraints:
          - engine.labels.availability_zone == ${AWS_REGION}a

volumes:
  acme-vol:
    name: ${ACME_VOL_NAME}
